// Generated by https://quicktype.io

import { Hospital } from "../hospital.interface";
import { Usuario } from "../usuario.model";

export interface CreateHospitalResponse {
  msg:            string;
  hospital:       Hospital;
  usuarioCreador: Usuario;
}
