// Generated by https://quicktype.io

import { Medico } from "../medico.interface";
import { Usuario } from "../usuario.model";

export interface CreateMedicoResponse {
  msg:            string;
  medico:         Medico;
  usuarioCreador: Usuario;
}
