// Generated by https://quicktype.io

import { Usuario } from "../usuario.model";

export interface DeleteUserResponse {
  msg:                string;
  usuario:            Usuario;
  usuarioAutenticado: Usuario;
}
