// Generated by https://quicktype.io

import { Usuario } from "../usuario.model";


export interface GetUsersResponse {
  total:              number;
  usuarios:           Usuario[];
  usuarioAutenticado: Usuario;
}
