// Generated by https://quicktype.io

import { Hospital } from "../hospital.interface";
import { Usuario } from "../usuario.model";

export interface GetHospitalsResponse {
  total:              number;
  hospitales:         Hospital[];
  usuarioAutenticado: Usuario;
}
