// Generated by https://quicktype.io

export interface SearchMedicalsResponse {
  total:   number;
  results: Result[];
}

interface Result {
  _id:      string;
  nombre:   string;
  usuario:  Usuario;
  hospital: Hospital;
  img:      string;
}

interface Hospital {
  _id:    string;
  nombre: string;
}

interface Usuario {
  _id:    string;
  nombre: string;
  img:    string;
}
