// Generated by https://quicktype.io

import { Hospital } from "../hospital.interface";
import { Medico } from "../medico.interface";
import { Usuario } from "../usuario.model";

export interface SearchAllResponse {
  totalResultados: number;
  totalUsuarios:   number;
  totalHospitales: number;
  totalMedicos:    number;
  usuarios:        Usuario[];
  hospitales:      Hospital[];
  medicos:         Medico[];
}
