// Generated by https://quicktype.io

import { Usuario } from "../usuario.model";

export interface UpdateUserResponse {
  msg:                string;
  usuario:            Usuario;
  usuarioAutenticado: Usuario;
}
