// Generated by https://quicktype.io

export interface UpdateHospitalResponse {
  msg:      string;
  hospital: Hospital;
}

interface Hospital {
  _id:     string;
  nombre:  string;
  usuario: string;
  img:     string;
}
