// Generated by https://quicktype.io

import { Usuario } from "./usuario.interface";

export interface UploadImageResponse {
  msg:                 string;
  coleccion:           string;
  id:                  string;
  modelo:              Usuario;
  usuarioQueActualizo: Usuario;
}
