// Generated by https://quicktype.io

import { Usuario } from "../../models/interfaces/usuario.interface";


export interface LoginResponse {
  usuario: Usuario;
  token:   string;
  menu:    Menu[];
}

export interface Menu {
  title:   string;
  icon:    string;
  submenu: Submenu[];
}

export interface Submenu {
  title: string;
  url:   string;
}
